on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore Palworld.RESTSharp/Palworld.RESTSharp.csproj

    - name: Build
      run: dotnet build --no-restore --configuration Release --property:DocumentationFile=bin/Release/netstandard2.1/Palworld.RESTSharp.xml Palworld.RESTSharp/Palworld.RESTSharp.csproj

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output nupkg --property:PackageVersion=${{ github.ref_name }} Palworld.RESTSharp/Palworld.RESTSharp.csproj

    - name: Publish to NuGet
      run: dotnet nuget push "nupkg/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETKEY }}
      if: startsWith(github.ref, 'refs/tags/')
